In [441]:
import numpy as np
import pandas as pd
import sklearn

In [442]:
df1 = pd.read_csv('spam.csv', encoding='latin1')
df1

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [443]:
df1.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)
df1

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [444]:
df1['v2'] = df1['v2'].str.lower()
df1

v1                                                 v2
0      ham  go until jurong point, crazy.. available only ...
1      ham                      ok lar... joking wif u oni...
2     spam  free entry in 2 a wkly comp to win fa cup fina...
3      ham  u dun say so early hor... u c already then say...
4      ham  nah i don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  this is the 2nd time we have tried 2 contact u...
5568   ham              will ì_ b going to esplanade fr home?
5569   ham  pity, * was in mood for that. so...any other s...
5570   ham  the guy did some bitching but i acted like i'd...
5571   ham                         rofl. its true to its name

[5572 rows x 2 columns]

In [445]:
import re
df1['v2'] = df1['v2'].apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', x))
df1['v2'] = df1['v2'].apply(lambda x: re.sub(r'\d+', '', x))
df1

v1                                                 v2
0      ham  go until jurong point crazy available only in ...
1      ham                            ok lar joking wif u oni
2     spam  free entry in  a wkly comp to win fa cup final...
3      ham        u dun say so early hor u c already then say
4      ham  nah i dont think he goes to usf he lives aroun...
...    ...                                                ...
5567  spam  this is the nd time we have tried  contact u u...
5568   ham                 will  b going to esplanade fr home
5569   ham  pity  was in mood for that soany other suggest...
5570   ham  the guy did some bitching but i acted like id ...
5571   ham                          rofl its true to its name

[5572 rows x 2 columns]

In [446]:
df1['v1'] = df1.v1.map({'spam':0, 'ham':1})
df1

v1                                                 v2
0      1  go until jurong point crazy available only in ...
1      1                            ok lar joking wif u oni
2      0  free entry in  a wkly comp to win fa cup final...
3      1        u dun say so early hor u c already then say
4      1  nah i dont think he goes to usf he lives aroun...
...   ..                                                ...
5567   0  this is the nd time we have tried  contact u u...
5568   1                 will  b going to esplanade fr home
5569   1  pity  was in mood for that soany other suggest...
5570   1  the guy did some bitching but i acted like id ...
5571   1                          rofl its true to its name

[5572 rows x 2 columns]

In [447]:
X = df1['v2'].values
y = df1['v1'].values
y = y.astype('int')

In [448]:
print("X")
print(X)
print("y")
print(y)

X
['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat'
 'ok lar joking wif u oni'
 'free entry in  a wkly comp to win fa cup final tkts st may  text fa to  to receive entry questionstd txt ratetcs apply overs'
 ... 'pity  was in mood for that soany other suggestions'
 'the guy did some bitching but i acted like id be interested in buying something else next week and he gave it to us for free'
 'rofl its true to its name']
y
[1 1 0 ... 1 1 1]


In [449]:
from sklearn.feature_extraction.text import CountVectorizer 
vec = CountVectorizer()

In [450]:
vec.fit(X)
vec.vocabulary_

{'go': 2846,
 'until': 7756,
 'jurong': 3740,
 'point': 5490,
 'crazy': 1557,
 'available': 489,
 'only': 5076,
 'in': 3457,
 'bugis': 944,
 'great': 2942,
 'world': 8254,
 'la': 3893,
 'buffet': 942,
 'cine': 1274,
 'there': 7329,
 'got': 2903,
 'amore': 247,
 'wat': 8003,
 'ok': 5036,
 'lar': 3929,
 'joking': 3708,
 'wif': 8144,
 'oni': 5070,
 'free': 2635,
 'entry': 2219,
 'wkly': 8205,
 'comp': 1390,
 'to': 7457,
 'win': 8159,
 'fa': 2355,
 'cup': 1614,
 'final': 2481,
 'tkts': 7446,
 'st': 6840,
 'may': 4373,
 'text': 7272,
 'receive': 5893,
 'questionstd': 5784,
 'txt': 7655,
 'ratetcs': 5837,
 'apply': 339,
 'overs': 5178,
 'dun': 2070,
 'say': 6242,
 'so': 6659,
 'early': 2092,
 'hor': 3279,
 'already': 220,
 'then': 7324,
 'nah': 4734,
 'dont': 1979,
 'think': 7353,
 'he': 3100,
 'goes': 2859,
 'usf': 7806,
 'lives': 4096,
 'around': 390,
 'here': 3155,
 'though': 7376,
 'freemsg': 2643,
 'hey': 3174,
 'darling': 1677,
 'its': 3613,
 'been': 648,
 'weeks': 8059,
 'now': 4931,


In [451]:
X_transformed=vec.transform(X)
X_transformed

<5572x8512 sparse matrix of type '<class 'numpy.int64'>'
	with 70621 stored elements in Compressed Sparse Row format>

In [452]:

vec = CountVectorizer(stop_words='english' )
vec.fit(X)
vec.vocabulary_

{'jurong': 3613,
 'point': 5312,
 'crazy': 1500,
 'available': 457,
 'bugis': 896,
 'great': 2841,
 'world': 7993,
 'la': 3765,
 'buffet': 894,
 'cine': 1220,
 'got': 2802,
 'amore': 229,
 'wat': 7763,
 'ok': 4875,
 'lar': 3801,
 'joking': 3581,
 'wif': 7887,
 'oni': 4906,
 'free': 2541,
 'entry': 2144,
 'wkly': 7944,
 'comp': 1335,
 'win': 7901,
 'fa': 2272,
 'cup': 1556,
 'final': 2394,
 'tkts': 7223,
 'st': 6639,
 'text': 7066,
 'receive': 5712,
 'questionstd': 5605,
 'txt': 7424,
 'ratetcs': 5658,
 'apply': 311,
 'overs': 5005,
 'dun': 2005,
 'say': 6060,
 'early': 2025,
 'hor': 3166,
 'nah': 4587,
 'dont': 1916,
 'think': 7137,
 'goes': 2758,
 'usf': 7569,
 'lives': 3965,
 'freemsg': 2549,
 'hey': 3064,
 'darling': 1619,
 'weeks': 7818,
 'word': 7979,
 'id': 3282,
 'like': 3915,
 'fun': 2610,
 'tb': 6994,
 'xxx': 8121,
 'std': 6685,
 'chgs': 1165,
 'send': 6150,
 'rcv': 5669,
 'brother': 863,
 'speak': 6554,
 'treat': 7353,
 'aids': 158,
 'patent': 5103,
 'request': 5823,
 'melle'

In [453]:

print(vec.get_feature_names_out())
print(len(vec.get_feature_names_out()))

['aa' 'aah' 'aaniye' ... 'zouk' 'zs' 'zyada']
8245


In [454]:
X_transformed=vec.transform(X)
X_transformed

<5572x8245 sparse matrix of type '<class 'numpy.int64'>'
	with 40985 stored elements in Compressed Sparse Row format>

**Having problem in this,when i print X before converting toarray() it prints the values but after that it converts all to zero,thats why not getting accuracy.**

In [455]:



X=X_transformed.todense()
X

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [456]:
pd.DataFrame(X, columns=vec.get_feature_names_out())

aa  aah  aaniye  aaooooright  aathilove  aathiwhere  ab  abbey  abdomen  \
0      0    0       0            0          0           0   0      0        0   
1      0    0       0            0          0           0   0      0        0   
2      0    0       0            0          0           0   0      0        0   
3      0    0       0            0          0           0   0      0        0   
4      0    0       0            0          0           0   0      0        0   
...   ..  ...     ...          ...        ...         ...  ..    ...      ...   
5567   0    0       0            0          0           0   0      0        0   
5568   0    0       0            0          0           0   0      0        0   
5569   0    0       0            0          0           0   0      0        0   
5570   0    0       0            0          0           0   0      0        0   
5571   0    0       0            0          0           0   0      0        0   

      abeg  ...  zeros  zf  zhong  zindgi  zoe  zogtorius  zoom  zouk  zs  \
0        0  ...      0   0      0       0    0          0     0     0   0   
1        0  ...      0   0      0       0    0          0     0     0   0   
2        0  ...      0   0      0       0    0          0     0     0   0   
3        0  ...      0   0      0       0    0          0     0     0   0   
4        0  ...      0   0      0       0    0          0     0     0   0   
...    ...  ...    ...  ..    ...     ...  ...        ...   ...   ...  ..   
5567     0  ...      0   0      0       0    0          0     0     0   0   
5568     0  ...      0   0      0       0    0          0     0     0   0   
5569     0  ...      0   0      0       0    0          0     0     0   0   
5570     0  ...      0   0      0       0    0          0     0     0   0   
5571     0  ...      0   0      0       0    0          0     0     0   0   

      zyada  
0         0  
1         0  
2         0  
3         0  
4         0  
...     ...  
5567      0  
5568      0  
5569      0  
5570      0  
5571      0  

[5572 rows x 8245 columns]

In [457]:
test_docs = pd.read_csv('Spam_test.csv')
test_docs

v1                                   v2
0  ham  Please come.Lets do our Assignment.
1  ham        Okay we will meet there soon.

In [458]:
test_numpy_array = test_docs.values
X_test = test_numpy_array[:,0]
Y_test = test_numpy_array[:,1]

Y_test = Y_test.astype('str')
print("X_test")
print(X_test)
print("Y_test")
print(Y_test)

X_test
['ham' 'ham']
Y_test
['Please come.Lets do our Assignment.' 'Okay we will meet there soon.']


In [459]:
X_test_transformed=vec.transform(X_test)
X_test_transformed

<2x8245 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

**Having problem in this,when i print X before converting toarray() it prints the values but after that it converts all to zero,thats why not getting accuracy.**

In [460]:
X_test=X_test_transformed.toarray()
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [461]:
from sklearn.metrics import accuracy_score

# Assuming you have the predicted labels in y_pred and the actual labels in y_true
accuracy = accuracy_score(Y_test, Y_test)
print("Accuracy:", accuracy)

Accuracy: 1.0
